// Code generated by "bwsetter -type=float64"; DO NOT EDIT; bwsetter: go get -type=float64 -set=Float64Set -test%!(EXTRA string=github.com/baza-winner/bwcore/bwsetter)

package bwset

import (
	bwjson "github.com/baza-winner/bwcore/bwjson"
	"sort"
	"strconv"
)

// Float64Set - множество значений типа float64 с поддержкой интерфейсов Stringer и github.com/baza-winner/bwcore/bwjson.Jsonable
type Float64Set map[float64]struct{}

// Float64SetFrom - конструктор Float64Set
func Float64SetFrom(kk ...float64) Float64Set {
	result := Float64Set{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// Float64SetFromSlice - конструктор Float64Set
func Float64SetFromSlice(kk []float64) Float64Set {
	result := Float64Set{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// Float64SetFromSet - конструктор Float64Set
func Float64SetFromSet(s Float64Set) Float64Set {
	result := Float64Set{}
	for k, _ := range s {
		result[k] = struct{}{}
	}
	return result
}

// Copy - создает независимую копию
func (v Float64Set) Copy() Float64Set {
	return Float64SetFromSet(v)
}

// ToSlice - возвращает в виде []float64
func (v Float64Set) ToSlice() []float64 {
	result := _float64Slice{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Sort(result)
	return result
}

func _Float64SetToSliceTestHelper(kk []float64) []float64 {
	return Float64SetFromSlice(kk).ToSlice()
}

// String - поддержка интерфейса Stringer
func (v Float64Set) String() string {
	return bwjson.PrettyJsonOf(v)
}

// DataForJson - поддержка интерфейса bwjson.Jsonable
func (v Float64Set) DataForJson() interface{} {
	result := []interface{}{}
	for k, _ := range v {
		result = append(result, k)
	}
	return result
}

// ToSliceOfStrings - возвращает []string строковых представлений элементов множества
func (v Float64Set) ToSliceOfStrings() []string {
	result := []string{}
	for k, _ := range v {
		result = append(result, strconv.FormatFloat(float64(k), byte(0x66), -1, 64))
	}
	sort.Strings(result)
	return result
}

// Has - возвращает true, если множество содержит заданный элемент, в противном случае - false
func (v Float64Set) Has(k float64) bool {
	_, ok := v[k]
	return ok
}

/*
HasAny - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Float64Set) HasAny(kk ...float64) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSlice - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Float64Set) HasAnyOfSlice(kk []float64) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSet - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Float64Set) HasAnyOfSet(s Float64Set) bool {
	for k, _ := range s {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasEach - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Float64Set) HasEach(kk ...float64) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSlice - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Float64Set) HasEachOfSlice(kk []float64) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSet - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Float64Set) HasEachOfSet(s Float64Set) bool {
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

// Add - добавляет элементы в множество v
func (v Float64Set) Add(kk ...float64) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Float64Set) _AddTestHelper(kk ...float64) Float64Set {
	result := v.Copy()
	result.Add(kk...)
	return result
}

// AddSlice - добавляет элементы в множество v
func (v Float64Set) AddSlice(kk []float64) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Float64Set) _AddSliceTestHelper(kk []float64) Float64Set {
	result := v.Copy()
	result.AddSlice(kk)
	return result
}

// AddSet - добавляет элементы в множество v
func (v Float64Set) AddSet(s Float64Set) {
	for k, _ := range s {
		v[k] = struct{}{}
	}
}

func (v Float64Set) _AddSetTestHelper(s Float64Set) Float64Set {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Del - удаляет элементы из множествa v
func (v Float64Set) Del(kk ...float64) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Float64Set) _DelTestHelper(kk ...float64) Float64Set {
	result := v.Copy()
	result.Del(kk...)
	return result
}

// DelSlice - удаляет элементы из множествa v
func (v Float64Set) DelSlice(kk []float64) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Float64Set) _DelSliceTestHelper(kk []float64) Float64Set {
	result := v.Copy()
	result.DelSlice(kk)
	return result
}

// DelSet - удаляет элементы из множествa v
func (v Float64Set) DelSet(s Float64Set) {
	for k, _ := range s {
		delete(v, k)
	}
}

func (v Float64Set) _DelSetTestHelper(s Float64Set) Float64Set {
	result := v.Copy()
	result.DelSet(s)
	return result
}

// Union - возвращает результат объединения двух множеств. Исходные множества остаются без изменений
func (v Float64Set) Union(s Float64Set) Float64Set {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Intersect - возвращает результат пересечения двух множеств. Исходные множества остаются без изменений
func (v Float64Set) Intersect(s Float64Set) Float64Set {
	result := Float64Set{}
	for k, _ := range v {
		if _, ok := s[k]; ok {
			result[k] = struct{}{}
		}
	}
	return result
}

// Subtract - возвращает результат вычитания двух множеств. Исходные множества остаются без изменений
func (v Float64Set) Subtract(s Float64Set) Float64Set {
	result := Float64Set{}
	for k, _ := range v {
		if _, ok := s[k]; !ok {
			result[k] = struct{}{}
		}
	}
	return result
}

type _float64Slice []float64

func (v _float64Slice) Len() int {
	return len(v)
}

func (v _float64Slice) Swap(i int, j int) {
	v[i], v[j] = v[j], v[i]
}

func (v _float64Slice) Less(i int, j int) bool {
	return v[i] < v[j]
}
