// Code generated by "bwsetter -type=int64"; DO NOT EDIT; bwsetter: go get -type=int64 -set=Int64Set -test%!(EXTRA string=github.com/baza-winner/bwcore/bwsetter)

package bwset

import (
	bwjson "github.com/baza-winner/bwcore/bwjson"
	"sort"
	"strconv"
)

// Int64Set - множество значений типа int64 с поддержкой интерфейсов Stringer и github.com/baza-winner/bwcore/bwjson.Jsonable
type Int64Set map[int64]struct{}

// Int64SetFrom - конструктор Int64Set
func Int64SetFrom(kk ...int64) Int64Set {
	result := Int64Set{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// Int64SetFromSlice - конструктор Int64Set
func Int64SetFromSlice(kk []int64) Int64Set {
	result := Int64Set{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// Int64SetFromSet - конструктор Int64Set
func Int64SetFromSet(s Int64Set) Int64Set {
	result := Int64Set{}
	for k, _ := range s {
		result[k] = struct{}{}
	}
	return result
}

// Copy - создает независимую копию
func (v Int64Set) Copy() Int64Set {
	return Int64SetFromSet(v)
}

// ToSlice - возвращает в виде []int64
func (v Int64Set) ToSlice() []int64 {
	result := _int64Slice{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Sort(result)
	return result
}

func _Int64SetToSliceTestHelper(kk []int64) []int64 {
	return Int64SetFromSlice(kk).ToSlice()
}

// String - поддержка интерфейса Stringer
func (v Int64Set) String() string {
	return bwjson.PrettyJsonOf(v)
}

// DataForJSON - поддержка интерфейса bwjson.Jsonable
func (v Int64Set) DataForJSON() interface{} {
	result := []interface{}{}
	for k, _ := range v {
		result = append(result, k)
	}
	return result
}

// ToSliceOfStrings - возвращает []string строковых представлений элементов множества
func (v Int64Set) ToSliceOfStrings() []string {
	result := []string{}
	for k, _ := range v {
		result = append(result, strconv.FormatInt(int64(k), 10))
	}
	sort.Strings(result)
	return result
}

// Has - возвращает true, если множество содержит заданный элемент, в противном случае - false
func (v Int64Set) Has(k int64) bool {
	_, ok := v[k]
	return ok
}

/*
HasAny - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Int64Set) HasAny(kk ...int64) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSlice - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Int64Set) HasAnyOfSlice(kk []int64) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSet - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v Int64Set) HasAnyOfSet(s Int64Set) bool {
	for k, _ := range s {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasEach - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Int64Set) HasEach(kk ...int64) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSlice - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Int64Set) HasEachOfSlice(kk []int64) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSet - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v Int64Set) HasEachOfSet(s Int64Set) bool {
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

// Add - добавляет элементы в множество v
func (v Int64Set) Add(kk ...int64) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Int64Set) _AddTestHelper(kk ...int64) Int64Set {
	result := v.Copy()
	result.Add(kk...)
	return result
}

// AddSlice - добавляет элементы в множество v
func (v Int64Set) AddSlice(kk []int64) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v Int64Set) _AddSliceTestHelper(kk []int64) Int64Set {
	result := v.Copy()
	result.AddSlice(kk)
	return result
}

// AddSet - добавляет элементы в множество v
func (v Int64Set) AddSet(s Int64Set) {
	for k, _ := range s {
		v[k] = struct{}{}
	}
}

func (v Int64Set) _AddSetTestHelper(s Int64Set) Int64Set {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Del - удаляет элементы из множествa v
func (v Int64Set) Del(kk ...int64) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Int64Set) _DelTestHelper(kk ...int64) Int64Set {
	result := v.Copy()
	result.Del(kk...)
	return result
}

// DelSlice - удаляет элементы из множествa v
func (v Int64Set) DelSlice(kk []int64) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v Int64Set) _DelSliceTestHelper(kk []int64) Int64Set {
	result := v.Copy()
	result.DelSlice(kk)
	return result
}

// DelSet - удаляет элементы из множествa v
func (v Int64Set) DelSet(s Int64Set) {
	for k, _ := range s {
		delete(v, k)
	}
}

func (v Int64Set) _DelSetTestHelper(s Int64Set) Int64Set {
	result := v.Copy()
	result.DelSet(s)
	return result
}

// Union - возвращает результат объединения двух множеств. Исходные множества остаются без изменений
func (v Int64Set) Union(s Int64Set) Int64Set {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Intersect - возвращает результат пересечения двух множеств. Исходные множества остаются без изменений
func (v Int64Set) Intersect(s Int64Set) Int64Set {
	result := Int64Set{}
	for k, _ := range v {
		if _, ok := s[k]; ok {
			result[k] = struct{}{}
		}
	}
	return result
}

// Subtract - возвращает результат вычитания двух множеств. Исходные множества остаются без изменений
func (v Int64Set) Subtract(s Int64Set) Int64Set {
	result := Int64Set{}
	for k, _ := range v {
		if _, ok := s[k]; !ok {
			result[k] = struct{}{}
		}
	}
	return result
}

type _int64Slice []int64

func (v _int64Slice) Len() int {
	return len(v)
}

func (v _int64Slice) Swap(i int, j int) {
	v[i], v[j] = v[j], v[i]
}

func (v _int64Slice) Less(i int, j int) bool {
	return v[i] < v[j]
}
