// Code generated by "bwsetter -type=interface{}"; DO NOT EDIT; bwsetter: go get -type=interface{} -set=Interface -test -nosort%!(EXTRA string=github.com/baza-winner/bwcore/bwsetter)

package bwset

import (
	bwjson "github.com/baza-winner/bwcore/bwjson"
	bwtesting "github.com/baza-winner/bwcore/bwtesting"
	"testing"
)

func TestInterface(t *testing.T) {
	bwtesting.BwRunTests(t, InterfaceFrom, map[string]bwtesting.TestCaseStruct{"InterfaceFrom": {
		In: []interface{}{[]interface{}{_InterfaceTestItemA, _InterfaceTestItemB}},
		Out: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, InterfaceFromSlice, map[string]bwtesting.TestCaseStruct{"InterfaceFromSlice": {
		In: []interface{}{[]interface{}{_InterfaceTestItemA, _InterfaceTestItemB}},
		Out: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, InterfaceFromSet, map[string]bwtesting.TestCaseStruct{"InterfaceFromSet": {
		In: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}},
		Out: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Interface.Copy, map[string]bwtesting.TestCaseStruct{"Interface.Copy": {
		In: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}},
		Out: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Interface.ToSlice, map[string]bwtesting.TestCaseStruct{"Interface.ToSlice": {
		In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}},
		Out: []interface{}{[]interface{}{_InterfaceTestItemA}},
	}})
	bwtesting.BwRunTests(t, Interface.String, map[string]bwtesting.TestCaseStruct{"Interface.String": {
		In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}},
		Out: []interface{}{bwjson.PrettyJson([]interface{}{_InterfaceTestItemA})},
	}})
	bwtesting.BwRunTests(t, Interface.DataForJSON, map[string]bwtesting.TestCaseStruct{"Interface.DataForJSON": {
		In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}},
		Out: []interface{}{[]interface{}{_InterfaceTestItemA}},
	}})
	bwtesting.BwRunTests(t, Interface.ToSliceOfStrings, map[string]bwtesting.TestCaseStruct{"Interface.ToSliceOfStrings": {
		In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}},
		Out: []interface{}{[]string{bwjson.PrettyJson(_InterfaceTestItemA)}},
	}})
	bwtesting.BwRunTests(t, Interface.Has, map[string]bwtesting.TestCaseStruct{
		"Interface.Has: false": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, _InterfaceTestItemB},
			Out: []interface{}{false},
		},
		"Interface.Has: true": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, _InterfaceTestItemA},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Interface.HasAny, map[string]bwtesting.TestCaseStruct{
		"Interface.HasAny: empty": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, []interface{}{}},
			Out: []interface{}{false},
		},
		"Interface.HasAny: false": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, []interface{}{_InterfaceTestItemB}},
			Out: []interface{}{false},
		},
		"Interface.HasAny: true": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, []interface{}{_InterfaceTestItemA, _InterfaceTestItemB}},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Interface.HasAnyOfSlice, map[string]bwtesting.TestCaseStruct{
		"Interface.HasAnyOfSlice: empty": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, []interface{}{}},
			Out: []interface{}{false},
		},
		"Interface.HasAnyOfSlice: false": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, []interface{}{_InterfaceTestItemB}},
			Out: []interface{}{false},
		},
		"Interface.HasAnyOfSlice: true": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, []interface{}{_InterfaceTestItemA, _InterfaceTestItemB}},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Interface.HasAnyOfSet, map[string]bwtesting.TestCaseStruct{
		"Interface.HasAnyOfSet: empty": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, Interface{}},
			Out: []interface{}{false},
		},
		"Interface.HasAnyOfSet: false": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, Interface{_InterfaceTestItemB: struct{}{}}},
			Out: []interface{}{false},
		},
		"Interface.HasAnyOfSet: true": {
			In: []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, Interface{
				_InterfaceTestItemA: struct{}{},
				_InterfaceTestItemB: struct{}{},
			}},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Interface.HasEach, map[string]bwtesting.TestCaseStruct{
		"Interface.HasEach: empty": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, []interface{}{}},
			Out: []interface{}{true},
		},
		"Interface.HasEach: false": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, []interface{}{_InterfaceTestItemA, _InterfaceTestItemB}},
			Out: []interface{}{false},
		},
		"Interface.HasEach: true": {
			In: []interface{}{Interface{
				_InterfaceTestItemA: struct{}{},
				_InterfaceTestItemB: struct{}{},
			}, []interface{}{_InterfaceTestItemA, _InterfaceTestItemB}},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Interface.HasEachOfSlice, map[string]bwtesting.TestCaseStruct{
		"Interface.HasEachOfSlice: empty": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, []interface{}{}},
			Out: []interface{}{true},
		},
		"Interface.HasEachOfSlice: false": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, []interface{}{_InterfaceTestItemA, _InterfaceTestItemB}},
			Out: []interface{}{false},
		},
		"Interface.HasEachOfSlice: true": {
			In: []interface{}{Interface{
				_InterfaceTestItemA: struct{}{},
				_InterfaceTestItemB: struct{}{},
			}, []interface{}{_InterfaceTestItemA, _InterfaceTestItemB}},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Interface.HasEachOfSet, map[string]bwtesting.TestCaseStruct{
		"Interface.HasEachOfSet: empty": {
			In:  []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, Interface{}},
			Out: []interface{}{true},
		},
		"Interface.HasEachOfSet: false": {
			In: []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, Interface{
				_InterfaceTestItemA: struct{}{},
				_InterfaceTestItemB: struct{}{},
			}},
			Out: []interface{}{false},
		},
		"Interface.HasEachOfSet: true": {
			In: []interface{}{Interface{
				_InterfaceTestItemA: struct{}{},
				_InterfaceTestItemB: struct{}{},
			}, Interface{
				_InterfaceTestItemA: struct{}{},
				_InterfaceTestItemB: struct{}{},
			}},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Interface._AddTestHelper, map[string]bwtesting.TestCaseStruct{"Interface.Add": {
		In: []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, []interface{}{_InterfaceTestItemB}},
		Out: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Interface._AddSliceTestHelper, map[string]bwtesting.TestCaseStruct{"Interface.AddSlice": {
		In: []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, []interface{}{_InterfaceTestItemB}},
		Out: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Interface._AddSetTestHelper, map[string]bwtesting.TestCaseStruct{"Interface.AddSet": {
		In: []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, Interface{_InterfaceTestItemB: struct{}{}}},
		Out: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Interface._DelTestHelper, map[string]bwtesting.TestCaseStruct{"Interface.Del": {
		In: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}, []interface{}{_InterfaceTestItemB}},
		Out: []interface{}{Interface{_InterfaceTestItemA: struct{}{}}},
	}})
	bwtesting.BwRunTests(t, Interface._DelSliceTestHelper, map[string]bwtesting.TestCaseStruct{"Interface.DelSlice": {
		In: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}, []interface{}{_InterfaceTestItemB}},
		Out: []interface{}{Interface{_InterfaceTestItemA: struct{}{}}},
	}})
	bwtesting.BwRunTests(t, Interface._DelSetTestHelper, map[string]bwtesting.TestCaseStruct{"Interface.DelSet": {
		In: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}, Interface{_InterfaceTestItemB: struct{}{}}},
		Out: []interface{}{Interface{_InterfaceTestItemA: struct{}{}}},
	}})
	bwtesting.BwRunTests(t, Interface.Union, map[string]bwtesting.TestCaseStruct{"Interface.Union": {
		In: []interface{}{Interface{_InterfaceTestItemA: struct{}{}}, Interface{_InterfaceTestItemB: struct{}{}}},
		Out: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Interface.Intersect, map[string]bwtesting.TestCaseStruct{"Interface.Intersect": {
		In: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}, Interface{_InterfaceTestItemB: struct{}{}}},
		Out: []interface{}{Interface{_InterfaceTestItemB: struct{}{}}},
	}})
	bwtesting.BwRunTests(t, Interface.Subtract, map[string]bwtesting.TestCaseStruct{"Interface.Subtract": {
		In: []interface{}{Interface{
			_InterfaceTestItemA: struct{}{},
			_InterfaceTestItemB: struct{}{},
		}, Interface{_InterfaceTestItemB: struct{}{}}},
		Out: []interface{}{Interface{_InterfaceTestItemA: struct{}{}}},
	}})
}
