// Code generated by "bwsetter -type=string"; DO NOT EDIT; bwsetter: go get -type=string -set=StringSet -test%!(EXTRA string=github.com/baza-winner/bwcore/bwsetter)

package bwset

import (
	bwjson "github.com/baza-winner/bwcore/bwjson"
	"sort"
)

// StringSet - множество значений типа string с поддержкой интерфейсов Stringer и github.com/baza-winner/bwcore/bwjson.Jsonable
type StringSet map[string]struct{}

// StringSetFrom - конструктор StringSet
func StringSetFrom(kk ...string) StringSet {
	result := StringSet{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// StringSetFromSlice - конструктор StringSet
func StringSetFromSlice(kk []string) StringSet {
	result := StringSet{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// StringSetFromSet - конструктор StringSet
func StringSetFromSet(s StringSet) StringSet {
	result := StringSet{}
	for k, _ := range s {
		result[k] = struct{}{}
	}
	return result
}

// Copy - создает независимую копию
func (v StringSet) Copy() StringSet {
	return StringSetFromSet(v)
}

// ToSlice - возвращает в виде []string
func (v StringSet) ToSlice() []string {
	result := _stringSlice{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Sort(result)
	return result
}

func _StringSetToSliceTestHelper(kk []string) []string {
	return StringSetFromSlice(kk).ToSlice()
}

// String - поддержка интерфейса Stringer
func (v StringSet) String() string {
	return bwjson.PrettyJsonOf(v)
}

// DataForJson - поддержка интерфейса bwjson.Jsonable
func (v StringSet) DataForJson() interface{} {
	result := []interface{}{}
	for k, _ := range v {
		result = append(result, k)
	}
	return result
}

// ToSliceOfStrings - возвращает []string строковых представлений элементов множества
func (v StringSet) ToSliceOfStrings() []string {
	result := []string{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Strings(result)
	return result
}

// Has - возвращает true, если множество содержит заданный элемент, в противном случае - false
func (v StringSet) Has(k string) bool {
	_, ok := v[k]
	return ok
}

/*
HasAny - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v StringSet) HasAny(kk ...string) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSlice - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v StringSet) HasAnyOfSlice(kk []string) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSet - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v StringSet) HasAnyOfSet(s StringSet) bool {
	for k, _ := range s {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasEach - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v StringSet) HasEach(kk ...string) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSlice - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v StringSet) HasEachOfSlice(kk []string) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSet - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v StringSet) HasEachOfSet(s StringSet) bool {
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

// Add - добавляет элементы в множество v
func (v StringSet) Add(kk ...string) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v StringSet) _AddTestHelper(kk ...string) StringSet {
	result := v.Copy()
	result.Add(kk...)
	return result
}

// AddSlice - добавляет элементы в множество v
func (v StringSet) AddSlice(kk []string) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

func (v StringSet) _AddSliceTestHelper(kk []string) StringSet {
	result := v.Copy()
	result.AddSlice(kk)
	return result
}

// AddSet - добавляет элементы в множество v
func (v StringSet) AddSet(s StringSet) {
	for k, _ := range s {
		v[k] = struct{}{}
	}
}

func (v StringSet) _AddSetTestHelper(s StringSet) StringSet {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Del - удаляет элементы из множествa v
func (v StringSet) Del(kk ...string) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v StringSet) _DelTestHelper(kk ...string) StringSet {
	result := v.Copy()
	result.Del(kk...)
	return result
}

// DelSlice - удаляет элементы из множествa v
func (v StringSet) DelSlice(kk []string) {
	for _, k := range kk {
		delete(v, k)
	}
}

func (v StringSet) _DelSliceTestHelper(kk []string) StringSet {
	result := v.Copy()
	result.DelSlice(kk)
	return result
}

// DelSet - удаляет элементы из множествa v
func (v StringSet) DelSet(s StringSet) {
	for k, _ := range s {
		delete(v, k)
	}
}

func (v StringSet) _DelSetTestHelper(s StringSet) StringSet {
	result := v.Copy()
	result.DelSet(s)
	return result
}

// Union - возвращает результат объединения двух множеств. Исходные множества остаются без изменений
func (v StringSet) Union(s StringSet) StringSet {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Intersect - возвращает результат пересечения двух множеств. Исходные множества остаются без изменений
func (v StringSet) Intersect(s StringSet) StringSet {
	result := StringSet{}
	for k, _ := range v {
		if _, ok := s[k]; ok {
			result[k] = struct{}{}
		}
	}
	return result
}

// Subtract - возвращает результат вычитания двух множеств. Исходные множества остаются без изменений
func (v StringSet) Subtract(s StringSet) StringSet {
	result := StringSet{}
	for k, _ := range v {
		if _, ok := s[k]; !ok {
			result[k] = struct{}{}
		}
	}
	return result
}

type _stringSlice []string

func (v _stringSlice) Len() int {
	return len(v)
}

func (v _stringSlice) Swap(i int, j int) {
	v[i], v[j] = v[j], v[i]
}

func (v _stringSlice) Less(i int, j int) bool {
	return v[i] < v[j]
}
