// Code generated by "bwsetter -type=uint64"; DO NOT EDIT; bwsetter: go get -type=uint64 -set=Uint64Set -test%!(EXTRA string=github.com/baza-winner/bwcore/bwsetter)

package bwset

import (
	bwjson "github.com/baza-winner/bwcore/bwjson"
	bwtesting "github.com/baza-winner/bwcore/bwtesting"
	"strconv"
	"testing"
)

func TestUint64Set(t *testing.T) {
	bwtesting.BwRunTests(t, Uint64SetFrom, map[string]bwtesting.TestCaseStruct{"Uint64SetFrom": {
		In: []interface{}{[]uint64{_Uint64SetTestItemA, _Uint64SetTestItemB}},
		Out: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Uint64SetFromSlice, map[string]bwtesting.TestCaseStruct{"Uint64SetFromSlice": {
		In: []interface{}{[]uint64{_Uint64SetTestItemA, _Uint64SetTestItemB}},
		Out: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Uint64SetFromSet, map[string]bwtesting.TestCaseStruct{"Uint64SetFromSet": {
		In: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}},
		Out: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Uint64Set.Copy, map[string]bwtesting.TestCaseStruct{"Uint64Set.Copy": {
		In: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}},
		Out: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Uint64Set.ToSlice, map[string]bwtesting.TestCaseStruct{"Uint64Set.ToSlice": {
		In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}},
		Out: []interface{}{[]uint64{_Uint64SetTestItemA}},
	}})
	bwtesting.BwRunTests(t, _Uint64SetToSliceTestHelper, map[string]bwtesting.TestCaseStruct{"_Uint64SetToSliceTestHelper": {
		In:  []interface{}{[]uint64{_Uint64SetTestItemB, _Uint64SetTestItemA}},
		Out: []interface{}{[]uint64{_Uint64SetTestItemA, _Uint64SetTestItemB}},
	}})
	bwtesting.BwRunTests(t, Uint64Set.String, map[string]bwtesting.TestCaseStruct{"Uint64Set.String": {
		In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}},
		Out: []interface{}{bwjson.PrettyJson([]uint64{_Uint64SetTestItemA})},
	}})
	bwtesting.BwRunTests(t, Uint64Set.DataForJson, map[string]bwtesting.TestCaseStruct{"Uint64Set.DataForJson": {
		In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}},
		Out: []interface{}{[]interface{}{_Uint64SetTestItemA}},
	}})
	bwtesting.BwRunTests(t, Uint64Set.ToSliceOfStrings, map[string]bwtesting.TestCaseStruct{"Uint64Set.ToSliceOfStrings": {
		In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}},
		Out: []interface{}{[]string{strconv.FormatUint(uint64(_Uint64SetTestItemA), 10)}},
	}})
	bwtesting.BwRunTests(t, Uint64Set.Has, map[string]bwtesting.TestCaseStruct{
		"Uint64Set.Has: false": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, _Uint64SetTestItemB},
			Out: []interface{}{false},
		},
		"Uint64Set.Has: true": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, _Uint64SetTestItemA},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Uint64Set.HasAny, map[string]bwtesting.TestCaseStruct{
		"Uint64Set.HasAny: empty": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, []uint64{}},
			Out: []interface{}{false},
		},
		"Uint64Set.HasAny: false": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, []uint64{_Uint64SetTestItemB}},
			Out: []interface{}{false},
		},
		"Uint64Set.HasAny: true": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, []uint64{_Uint64SetTestItemA, _Uint64SetTestItemB}},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Uint64Set.HasAnyOfSlice, map[string]bwtesting.TestCaseStruct{
		"Uint64Set.HasAnyOfSlice: empty": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, []uint64{}},
			Out: []interface{}{false},
		},
		"Uint64Set.HasAnyOfSlice: false": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, []uint64{_Uint64SetTestItemB}},
			Out: []interface{}{false},
		},
		"Uint64Set.HasAnyOfSlice: true": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, []uint64{_Uint64SetTestItemA, _Uint64SetTestItemB}},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Uint64Set.HasAnyOfSet, map[string]bwtesting.TestCaseStruct{
		"Uint64Set.HasAnyOfSet: empty": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, Uint64Set{}},
			Out: []interface{}{false},
		},
		"Uint64Set.HasAnyOfSet: false": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, Uint64Set{_Uint64SetTestItemB: struct{}{}}},
			Out: []interface{}{false},
		},
		"Uint64Set.HasAnyOfSet: true": {
			In: []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, Uint64Set{
				_Uint64SetTestItemA: struct{}{},
				_Uint64SetTestItemB: struct{}{},
			}},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Uint64Set.HasEach, map[string]bwtesting.TestCaseStruct{
		"Uint64Set.HasEach: empty": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, []uint64{}},
			Out: []interface{}{true},
		},
		"Uint64Set.HasEach: false": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, []uint64{_Uint64SetTestItemA, _Uint64SetTestItemB}},
			Out: []interface{}{false},
		},
		"Uint64Set.HasEach: true": {
			In: []interface{}{Uint64Set{
				_Uint64SetTestItemA: struct{}{},
				_Uint64SetTestItemB: struct{}{},
			}, []uint64{_Uint64SetTestItemA, _Uint64SetTestItemB}},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Uint64Set.HasEachOfSlice, map[string]bwtesting.TestCaseStruct{
		"Uint64Set.HasEachOfSlice: empty": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, []uint64{}},
			Out: []interface{}{true},
		},
		"Uint64Set.HasEachOfSlice: false": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, []uint64{_Uint64SetTestItemA, _Uint64SetTestItemB}},
			Out: []interface{}{false},
		},
		"Uint64Set.HasEachOfSlice: true": {
			In: []interface{}{Uint64Set{
				_Uint64SetTestItemA: struct{}{},
				_Uint64SetTestItemB: struct{}{},
			}, []uint64{_Uint64SetTestItemA, _Uint64SetTestItemB}},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Uint64Set.HasEachOfSet, map[string]bwtesting.TestCaseStruct{
		"Uint64Set.HasEachOfSet: empty": {
			In:  []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, Uint64Set{}},
			Out: []interface{}{true},
		},
		"Uint64Set.HasEachOfSet: false": {
			In: []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, Uint64Set{
				_Uint64SetTestItemA: struct{}{},
				_Uint64SetTestItemB: struct{}{},
			}},
			Out: []interface{}{false},
		},
		"Uint64Set.HasEachOfSet: true": {
			In: []interface{}{Uint64Set{
				_Uint64SetTestItemA: struct{}{},
				_Uint64SetTestItemB: struct{}{},
			}, Uint64Set{
				_Uint64SetTestItemA: struct{}{},
				_Uint64SetTestItemB: struct{}{},
			}},
			Out: []interface{}{true},
		},
	})
	bwtesting.BwRunTests(t, Uint64Set._AddTestHelper, map[string]bwtesting.TestCaseStruct{"Uint64Set.Add": {
		In: []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, []uint64{_Uint64SetTestItemB}},
		Out: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Uint64Set._AddSliceTestHelper, map[string]bwtesting.TestCaseStruct{"Uint64Set.AddSlice": {
		In: []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, []uint64{_Uint64SetTestItemB}},
		Out: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Uint64Set._AddSetTestHelper, map[string]bwtesting.TestCaseStruct{"Uint64Set.AddSet": {
		In: []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, Uint64Set{_Uint64SetTestItemB: struct{}{}}},
		Out: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Uint64Set._DelTestHelper, map[string]bwtesting.TestCaseStruct{"Uint64Set.Del": {
		In: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}, []uint64{_Uint64SetTestItemB}},
		Out: []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}},
	}})
	bwtesting.BwRunTests(t, Uint64Set._DelSliceTestHelper, map[string]bwtesting.TestCaseStruct{"Uint64Set.DelSlice": {
		In: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}, []uint64{_Uint64SetTestItemB}},
		Out: []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}},
	}})
	bwtesting.BwRunTests(t, Uint64Set._DelSetTestHelper, map[string]bwtesting.TestCaseStruct{"Uint64Set.DelSet": {
		In: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}, Uint64Set{_Uint64SetTestItemB: struct{}{}}},
		Out: []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}},
	}})
	bwtesting.BwRunTests(t, Uint64Set.Union, map[string]bwtesting.TestCaseStruct{"Uint64Set.Union": {
		In: []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}, Uint64Set{_Uint64SetTestItemB: struct{}{}}},
		Out: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}},
	}})
	bwtesting.BwRunTests(t, Uint64Set.Intersect, map[string]bwtesting.TestCaseStruct{"Uint64Set.Intersect": {
		In: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}, Uint64Set{_Uint64SetTestItemB: struct{}{}}},
		Out: []interface{}{Uint64Set{_Uint64SetTestItemB: struct{}{}}},
	}})
	bwtesting.BwRunTests(t, Uint64Set.Subtract, map[string]bwtesting.TestCaseStruct{"Uint64Set.Subtract": {
		In: []interface{}{Uint64Set{
			_Uint64SetTestItemA: struct{}{},
			_Uint64SetTestItemB: struct{}{},
		}, Uint64Set{_Uint64SetTestItemB: struct{}{}}},
		Out: []interface{}{Uint64Set{_Uint64SetTestItemA: struct{}{}}},
	}})
}
