version: '2'
services:
  main:
    container_name: ${mainContainerName}
    image: ${mainImageName}
    volumes:
      - ${_bwDir}:/home/dev/.bw
      - ${_bwFileSpec}:/home/dev/bw.bash
      - ..:/home/dev/proj
    stdin_open: true
    env_file:
      - main.env
