version: '2'
services:
  nginx:
    container_name: ${nginxContainerName}
    image: nginx:alpine
    volumes:
      - ${_bwNginxConfDir}:/etc/nginx/conf.bw
      - ${_bwSslFileSpecPrefix}crt:/etc/ssl/server.crt
      - ${_bwSslFileSpecPrefix}key:/etc/ssl/server.key
      - ..:/etc/nginx/html
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/main.conf:/etc/nginx/main.conf
