version: '2'
services:
  main:
    container_name: ${mainContainerName}
    image: ${mainImageName}
    volumes:
      - ${_bwDir}:/home/dev/.bw
      - ${_bwDir}/ssh/bw_dev_id_rsa.pub:/home/dev/.ssh/authorized_keys
      - ${_bwFileSpec}:/home/dev/bw.bash
      - ..:/home/dev/proj
    stdin_open: true
    ports:
      - "${ssh}:22"
