// Code generated by "stringer -type=parseState"; DO NOT EDIT.

package defparser

import "strconv"

const _parseState_name = "expectEOFexpectEOFOrSpaceexpectValueOrSpaceexpectValueOrSpaceOrArrayItemSeparatorexpectValueOrSpaceOrMapKeySeparatorexpectArrayItemSeparatorOrSpaceexpectMapKeySeparatorOrSpaceexpectRocketexpectMapKeyexpectWordexpectDigitexpectDigitOrUnderscoreOrDotexpectDigitOrUnderscoreexpectContentOfDoubleQuotedStringexpectContentOfSingleQuotedStringexpectEscapedContentOfDoubleQuotedStringexpectEscapedContentOfSingleQuotedStringexpectContentOfDoubleQuotedKeyexpectContentOfSingleQuotedKeyexpectEscapedContentOfDoubleQuotedKeyexpectEscapedContentOfSingleQuotedKeyexpectSpaceOrMapKeyexpectSpaceOrMapKeyOrMapValueSeparatorexpectSpaceOrQwItemOrDelimiterexpectEndOfQwItem"

var _parseState_index = [...]uint16{0, 9, 25, 43, 81, 116, 147, 175, 187, 199, 209, 220, 248, 271, 304, 337, 377, 417, 447, 477, 514, 551, 570, 608, 638, 655}

func (i parseState) String() string {
	if i >= parseState(len(_parseState_index)-1) {
		return "parseState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _parseState_name[_parseState_index[i]:_parseState_index[i+1]]
}
