// Code generated by "stringer -type=ParseStackItemType"; DO NOT EDIT.

package defparser

import "strconv"

const _ParseStackItemType_name = "parseStackItemArrayparseStackItemQwparseStackItemQwItemparseStackItemMapparseStackItemNumberparseStackItemStringparseStackItemWordparseStackItemKey"

var _ParseStackItemType_index = [...]uint8{0, 19, 35, 55, 72, 92, 112, 130, 147}

func (i ParseStackItemType) String() string {
	if i >= ParseStackItemType(len(_ParseStackItemType_index)-1) {
		return "ParseStackItemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParseStackItemType_name[_ParseStackItemType_index[i]:_ParseStackItemType_index[i+1]]
}
