// Code generated by "stringer -type=parseSecondaryState"; DO NOT EDIT.

package defparser

import "strconv"

const _parseSecondaryState_name = "noSecondaryStateorSpaceorMapKeySeparatororArrayItemSeparatororUnderscoreOrDotorUnderscoredoubleQuotedsingleQuotedorMapValueSeparator"

var _parseSecondaryState_index = [...]uint8{0, 16, 23, 40, 60, 77, 89, 101, 113, 132}

func (i parseSecondaryState) String() string {
	if i >= parseSecondaryState(len(_parseSecondaryState_index)-1) {
		return "parseSecondaryState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _parseSecondaryState_name[_parseSecondaryState_index[i]:_parseSecondaryState_index[i+1]]
}
