// Code generated by "stringer -type=defErrorType"; DO NOT EDIT.

package defvalid

import "strconv"

const _defErrorType_name = "defError_below_defErrorHasUnexpectedValuedefError_above_"

var _defErrorType_index = [...]uint8{0, 15, 41, 56}

func (i defErrorType) String() string {
	if i >= defErrorType(len(_defErrorType_index)-1) {
		return "defErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _defErrorType_name[_defErrorType_index[i]:_defErrorType_index[i+1]]
}
