// Code generated by "stringer -type=deftypeItem"; DO NOT EDIT.

package defvalid

import "strconv"

const _deftypeItem_name = "deftype_below_deftypeBooldeftypeStringdeftypeIntdeftypeNumberdeftypeMapdeftypeArraydeftypeOrArrayOfdeftype_above_"

var _deftypeItem_index = [...]uint8{0, 14, 25, 38, 48, 61, 71, 83, 99, 113}

func (i deftypeItem) String() string {
	if i >= deftypeItem(len(_deftypeItem_index)-1) {
		return "deftypeItem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _deftypeItem_name[_deftypeItem_index[i]:_deftypeItem_index[i+1]]
}
