// Code generated by "stringer -type=valueErrorType"; DO NOT EDIT.

package defvalid

import "strconv"

const _valueErrorType_name = "_valueErrorBelowvalueErrorIsNotOfTypevalueErrorHasUnexpectedKeysvalueErrorHasNoKeyvalueErrorHasNonSupportedValue_valueErrorAbove"

var _valueErrorType_index = [...]uint8{0, 16, 37, 64, 82, 112, 128}

func (i valueErrorType) String() string {
	if i >= valueErrorType(len(_valueErrorType_index)-1) {
		return "valueErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _valueErrorType_name[_valueErrorType_index[i]:_valueErrorType_index[i+1]]
}
