// Code generated by "stringer -type=RangeKindValue"; DO NOT EDIT.

package bwval

import "strconv"

const _RangeKindValue_name = "RangeNoRangeMinRangeMaxRangeMinMax"

var _RangeKindValue_index = [...]uint8{0, 7, 15, 23, 34}

func (i RangeKindValue) String() string {
	if i >= RangeKindValue(len(_RangeKindValue_index)-1) {
		return "RangeKindValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RangeKindValue_name[_RangeKindValue_index[i]:_RangeKindValue_index[i+1]]
}
