// Code generated by "stringer -type ValKind -trimprefix Val"; DO NOT EDIT.

package bwval

import "strconv"

const _ValKind_name = "UnknownNilBoolIntNumberStringArrayArrayOfMapKindAbove"

var _ValKind_index = [...]uint8{0, 7, 10, 14, 17, 23, 29, 34, 41, 44, 53}

func (i ValKind) String() string {
	if i >= ValKind(len(_ValKind_index)-1) {
		return "ValKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValKind_name[_ValKind_index[i]:_ValKind_index[i+1]]
}
