// Code generated by "stringer -type=ValKind"; DO NOT EDIT.

package bwval

import "strconv"

const _ValKind_name = "ValUnknownValBoolValIntValStringValMapValArray"

var _ValKind_index = [...]uint8{0, 10, 17, 23, 32, 38, 46}

func (i ValKind) String() string {
	if i >= ValKind(len(_ValKind_index)-1) {
		return "ValKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValKind_name[_ValKind_index[i]:_ValKind_index[i+1]]
}
