// Code generated by "stringer -type=varPathParseState,varPathItemType"; DO NOT EDIT.

package bwval

import "strconv"

const _varPathParseState_name = "vppsBeginvppsEndvppsDonevppsIdxvppsDigitvppsKeyvppsForceEnd"

var _varPathParseState_index = [...]uint8{0, 9, 16, 24, 31, 40, 47, 59}

func (i varPathParseState) String() string {
	if i >= varPathParseState(len(_varPathParseState_index)-1) {
		return "varPathParseState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _varPathParseState_name[_varPathParseState_index[i]:_varPathParseState_index[i+1]]
}

const _varPathItemType_name = "varPathItemHashvarPathItemIdxvarPathItemKeyvarPathItemPath"

var _varPathItemType_index = [...]uint8{0, 15, 29, 43, 58}

func (i varPathItemType) String() string {
	if i >= varPathItemType(len(_varPathItemType_index)-1) {
		return "varPathItemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _varPathItemType_name[_varPathItemType_index[i]:_varPathItemType_index[i+1]]
}
