// Code generated by "stringer -type=parseTertiaryState"; DO NOT EDIT.

package pathparse

import "strconv"

const _parseTertiaryState_name = "noTertiaryState"

var _parseTertiaryState_index = [...]uint8{0, 15}

func (i parseTertiaryState) String() string {
	if i >= parseTertiaryState(len(_parseTertiaryState_index)-1) {
		return "parseTertiaryState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _parseTertiaryState_name[_parseTertiaryState_index[i]:_parseTertiaryState_index[i+1]]
}
