// Code generated by "stringer -type=parsePrimaryState"; DO NOT EDIT.

package pathparse

import "strconv"

const _parsePrimaryState_name = "parsePrimaryStateBelowexpectEOFexpectPathSegmentexpectMapKeyexpectDigitexpectContentOfexpectEscapedContentOfparsePrimaryStateAbove"

var _parsePrimaryState_index = [...]uint8{0, 24, 33, 50, 62, 73, 88, 110, 134}

func (i parsePrimaryState) String() string {
	if i >= parsePrimaryState(len(_parsePrimaryState_index)-1) {
		return "parsePrimaryState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _parsePrimaryState_name[_parsePrimaryState_index[i]:_parsePrimaryState_index[i+1]]
}
