// Code generated by "stringer -type=pfaErrorType"; DO NOT EDIT.

package pathparse

import "strconv"

const _pfaErrorType_name = "pfaErrorBelowunexpectedRuneErrorfailedToGetNumberErrorpfaErrorAbove"

var _pfaErrorType_index = [...]uint8{0, 15, 34, 56, 71}

func (i pfaErrorType) String() string {
	if i >= pfaErrorType(len(_pfaErrorType_index)-1) {
		return "pfaErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _pfaErrorType_name[_pfaErrorType_index[i]:_pfaErrorType_index[i+1]]
}
