// Code generated by "stringer -type ParseValKind -trimprefix ParseVal"; DO NOT EDIT.

package bwparse

import "strconv"

const _ParseValKind_name = "NilBoolIntFloat64RangeStringIdMapArrayArrayOfStringPath"

var _ParseValKind_index = [...]uint8{0, 3, 7, 10, 17, 22, 28, 30, 33, 38, 51, 55}

func (i ParseValKind) String() string {
	if i >= ParseValKind(len(_ParseValKind_index)-1) {
		return "ParseValKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParseValKind_name[_ParseValKind_index[i]:_ParseValKind_index[i+1]]
}
