// Code generated by "stringer -type=valType"; DO NOT EDIT.

package core

import "strconv"

const _valType_name = "valTypeNilvalTypeSlicevalTypeMap"

var _valType_index = [...]uint8{0, 10, 22, 32}

func (i valType) String() string {
	if i >= valType(len(_valType_index)-1) {
		return "valType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _valType_name[_valType_index[i]:_valType_index[i+1]]
}
