// Code generated by "stringer -type=varPathParseState"; DO NOT EDIT.

package core

import "strconv"

const _varPathParseState_name = "vppsBeginvppsEndvppsDonevppsIdxvppsDigitvppsKeyvppsForceEnd"

var _varPathParseState_index = [...]uint8{0, 9, 16, 24, 31, 40, 47, 59}

func (i varPathParseState) String() string {
	if i >= varPathParseState(len(_varPathParseState_index)-1) {
		return "varPathParseState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _varPathParseState_name[_varPathParseState_index[i]:_varPathParseState_index[i+1]]
}
