version: '2'
services:
  nginx:
    container_name: ${_bwdevDockerContainerName}-nginx
    image: nginx:alpine
    volumes:
      - ..:/etc/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/main.conf:/etc/nginx/main.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${_bwDir}/https/server.crt:/etc/ssl/server.crt
      - ${_bwDir}/https/server.key:/etc/ssl/server.key
      - ./nginx/log:/var/log/nginx
    ports:
      - ${_bwdevDockerHttp}:80
      - ${_bwdevDockerHttps}:443
