// Code generated by "stringer -type=UnicodeCategory"; DO NOT EDIT.

package val

import "strconv"

const _UnicodeCategory_name = "SpaceLetterLowerUpperDigitOpenBracesPunctSymbol"

var _UnicodeCategory_index = [...]uint8{0, 5, 11, 16, 21, 26, 36, 41, 47}

func (i UnicodeCategory) String() string {
	if i >= UnicodeCategory(len(_UnicodeCategory_index)-1) {
		return "UnicodeCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnicodeCategory_name[_UnicodeCategory_index[i]:_UnicodeCategory_index[i+1]]
}
