// Code generated by "setter -type=parseStackItemType"; DO NOT EDIT; setter: go get github.com/baza-winner/bwcore/setter

package defparse

import (
	bwjson "github.com/baza-winner/bwcore/bwjson"
	"sort"
)

// parseStackItemTypeSet - множество значений типа parseStackItemType с поддержкой интерфейсов Stringer и github.com/baza-winner/bwcore/bwjson.Jsonable
type parseStackItemTypeSet map[parseStackItemType]struct{}

// parseStackItemTypeSetFrom - конструктор parseStackItemTypeSet
func parseStackItemTypeSetFrom(kk ...parseStackItemType) parseStackItemTypeSet {
	result := parseStackItemTypeSet{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// parseStackItemTypeSetFromSlice - конструктор parseStackItemTypeSet
func parseStackItemTypeSetFromSlice(kk []parseStackItemType) parseStackItemTypeSet {
	result := parseStackItemTypeSet{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// parseStackItemTypeSetFromSet - конструктор parseStackItemTypeSet
func parseStackItemTypeSetFromSet(s parseStackItemTypeSet) parseStackItemTypeSet {
	result := parseStackItemTypeSet{}
	for k, _ := range s {
		result[k] = struct{}{}
	}
	return result
}

// Copy - создает независимую копию
func (v parseStackItemTypeSet) Copy() parseStackItemTypeSet {
	return parseStackItemTypeSetFromSet(v)
}

// ToSlice - возвращает в виде []parseStackItemType
func (v parseStackItemTypeSet) ToSlice() []parseStackItemType {
	result := _parseStackItemTypeSlice{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Sort(result)
	return result
}

func _parseStackItemTypeSetToSliceTestHelper(kk []parseStackItemType) []parseStackItemType {
	return parseStackItemTypeSetFromSlice(kk).ToSlice()
}

// String - поддержка интерфейса Stringer
func (v parseStackItemTypeSet) String() string {
	return bwjson.PrettyJsonOf(v)
}

// GetDataForJson - поддержка интерфейса bwjson.Jsonable
func (v parseStackItemTypeSet) GetDataForJson() interface{} {
	result := []interface{}{}
	for k, _ := range v {
		result = append(result, k.String())
	}
	return result
}

// ToSliceOfStrings - возвращает []string строковых представлений элементов множества
func (v parseStackItemTypeSet) ToSliceOfStrings() []string {
	result := []string{}
	for k, _ := range v {
		result = append(result, k.String())
	}
	sort.Strings(result)
	return result
}

// Has - возвращает true, если множество содержит заданный элемент, в противном случае - false
func (v parseStackItemTypeSet) Has(k parseStackItemType) bool {
	_, ok := v[k]
	return ok
}

/*
HasAny - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v parseStackItemTypeSet) HasAny(kk ...parseStackItemType) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSlice - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v parseStackItemTypeSet) HasAnyOfSlice(kk []parseStackItemType) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSet - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v parseStackItemTypeSet) HasAnyOfSet(s parseStackItemTypeSet) bool {
	for k, _ := range s {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasEach - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v parseStackItemTypeSet) HasEach(kk ...parseStackItemType) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSlice - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v parseStackItemTypeSet) HasEachOfSlice(kk []parseStackItemType) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSet - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v parseStackItemTypeSet) HasEachOfSet(s parseStackItemTypeSet) bool {
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

// Add - добавляет элементы в множество v
func (v parseStackItemTypeSet) Add(kk ...parseStackItemType) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

// AddSlice - добавляет элементы в множество v
func (v parseStackItemTypeSet) AddSlice(kk []parseStackItemType) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

// AddSet - добавляет элементы в множество v
func (v parseStackItemTypeSet) AddSet(s parseStackItemTypeSet) {
	for k, _ := range s {
		v[k] = struct{}{}
	}
}

// Del - удаляет элементы из множествa v
func (v parseStackItemTypeSet) Del(kk ...parseStackItemType) {
	for _, k := range kk {
		delete(v, k)
	}
}

// DelSlice - удаляет элементы из множествa v
func (v parseStackItemTypeSet) DelSlice(kk []parseStackItemType) {
	for _, k := range kk {
		delete(v, k)
	}
}

// DelSet - удаляет элементы из множествa v
func (v parseStackItemTypeSet) DelSet(s parseStackItemTypeSet) {
	for k, _ := range s {
		delete(v, k)
	}
}

// Union - возвращает результат объединения двух множеств. Исходные множества остаются без изменений
func (v parseStackItemTypeSet) Union(s parseStackItemTypeSet) parseStackItemTypeSet {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Intersect - возвращает результат пересечения двух множеств. Исходные множества остаются без изменений
func (v parseStackItemTypeSet) Intersect(s parseStackItemTypeSet) parseStackItemTypeSet {
	result := parseStackItemTypeSet{}
	for k, _ := range v {
		if _, ok := s[k]; ok {
			result[k] = struct{}{}
		}
	}
	return result
}

// Subtract - возвращает результат вычитания двух множеств. Исходные множества остаются без изменений
func (v parseStackItemTypeSet) Subtract(s parseStackItemTypeSet) parseStackItemTypeSet {
	result := parseStackItemTypeSet{}
	for k, _ := range v {
		if _, ok := s[k]; !ok {
			result[k] = struct{}{}
		}
	}
	return result
}

type _parseStackItemTypeSlice []parseStackItemType

func (v _parseStackItemTypeSlice) Len() int {
	return len(v)
}

func (v _parseStackItemTypeSlice) Swap(i int, j int) {
	v[i], v[j] = v[j], v[i]
}

func (v _parseStackItemTypeSlice) Less(i int, j int) bool {
	return v[i] < v[j]
}
