// Code generated by "stringer -type=parseSecondaryState"; DO NOT EDIT.

package defparse

import "strconv"

const _parseSecondaryState_name = "anySecondaryStatenoSecondaryStateorSpaceorMapKeySeparatororArrayItemSeparatororUnderscoreOrDotorUnderscorestringTokenkeyTokenorMapValueSeparator"

var _parseSecondaryState_index = [...]uint8{0, 17, 33, 40, 57, 77, 94, 106, 117, 125, 144}

func (i parseSecondaryState) String() string {
	if i >= parseSecondaryState(len(_parseSecondaryState_index)-1) {
		return "parseSecondaryState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _parseSecondaryState_name[_parseSecondaryState_index[i]:_parseSecondaryState_index[i+1]]
}
