// Code generated by "stringer -type=parseStackItemType"; DO NOT EDIT.

package defparse

import "strconv"

const _parseStackItemType_name = "parseStackItem_below_parseStackItemKeyparseStackItemStringparseStackItemMapparseStackItemArrayparseStackItemQwparseStackItemQwItemparseStackItemNumberparseStackItemWordparseStackItem_above_"

var _parseStackItemType_index = [...]uint8{0, 21, 38, 58, 75, 94, 110, 130, 150, 168, 189}

func (i parseStackItemType) String() string {
	if i >= parseStackItemType(len(_parseStackItemType_index)-1) {
		return "parseStackItemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _parseStackItemType_name[_parseStackItemType_index[i]:_parseStackItemType_index[i+1]]
}
