// Code generated by "stringer -type=parsePrimaryState"; DO NOT EDIT.

package defparse

import "strconv"

const _parsePrimaryState_name = "parsePrimaryState_below_expectEOFexpectValueOrSpaceexpectArrayItemSeparatorOrSpaceexpectMapKeySeparatorOrSpaceexpectRocketexpectMapKeyexpectWordexpectDigitexpectContentOfexpectEscapedContentOfexpectSpaceOrMapKeyexpectSpaceOrQwItemOrDelimiterexpectEndOfQwItemparsePrimaryState_above_"

var _parsePrimaryState_index = [...]uint16{0, 24, 33, 51, 82, 110, 122, 134, 144, 155, 170, 192, 211, 241, 258, 282}

func (i parsePrimaryState) String() string {
	if i >= parsePrimaryState(len(_parsePrimaryState_index)-1) {
		return "parsePrimaryState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _parsePrimaryState_name[_parsePrimaryState_index[i]:_parsePrimaryState_index[i+1]]
}
