// Code generated by "stringer -type=ruleKind"; DO NOT EDIT.

package defparse

import "strconv"

const _ruleKind_name = "ruleNormalruleDefaultruleEof"

var _ruleKind_index = [...]uint8{0, 10, 21, 28}

func (i ruleKind) String() string {
	if i >= ruleKind(len(_ruleKind_index)-1) {
		return "ruleKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ruleKind_name[_ruleKind_index[i]:_ruleKind_index[i+1]]
}
