// Code generated by "setter -type=rune"; DO NOT EDIT; setter: go get github.com/baza-winner/bwcore/setter

package defparse

import (
	bwjson "github.com/baza-winner/bwcore/bwjson"
	"sort"
)

// runeSet - множество значений типа rune с поддержкой интерфейсов Stringer и github.com/baza-winner/bwcore/bwjson.Jsonable
type runeSet map[rune]struct{}

// runeSetFrom - конструктор runeSet
func runeSetFrom(kk ...rune) runeSet {
	result := runeSet{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// runeSetFromSlice - конструктор runeSet
func runeSetFromSlice(kk []rune) runeSet {
	result := runeSet{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

// runeSetFromSet - конструктор runeSet
func runeSetFromSet(s runeSet) runeSet {
	result := runeSet{}
	for k, _ := range s {
		result[k] = struct{}{}
	}
	return result
}

// Copy - создает независимую копию
func (v runeSet) Copy() runeSet {
	return runeSetFromSet(v)
}

// ToSlice - возвращает в виде []rune
func (v runeSet) ToSlice() []rune {
	result := _runeSlice{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Sort(result)
	return result
}

func _runeSetToSliceTestHelper(kk []rune) []rune {
	return runeSetFromSlice(kk).ToSlice()
}

// String - поддержка интерфейса Stringer
func (v runeSet) String() string {
	return bwjson.PrettyJsonOf(v)
}

// GetDataForJson - поддержка интерфейса bwjson.Jsonable
func (v runeSet) GetDataForJson() interface{} {
	result := []interface{}{}
	for k, _ := range v {
		result = append(result, string(k))
	}
	return result
}

// ToSliceOfStrings - возвращает []string строковых представлений элементов множества
func (v runeSet) ToSliceOfStrings() []string {
	result := []string{}
	for k, _ := range v {
		result = append(result, string(k))
	}
	sort.Strings(result)
	return result
}

// Has - возвращает true, если множество содержит заданный элемент, в противном случае - false
func (v runeSet) Has(k rune) bool {
	_, ok := v[k]
	return ok
}

/*
HasAny - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v runeSet) HasAny(kk ...rune) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSlice - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v runeSet) HasAnyOfSlice(kk []rune) bool {
	for _, k := range kk {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasAnyOfSet - возвращает true, если множество содержит хотя бы один из заданныx элементов, в противном случае - false.
HasAny(<пустой набор/множесто>) возвращает false
*/
func (v runeSet) HasAnyOfSet(s runeSet) bool {
	for k, _ := range s {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

/*
HasEach - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v runeSet) HasEach(kk ...rune) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSlice - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v runeSet) HasEachOfSlice(kk []rune) bool {
	for _, k := range kk {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

/*
HasEachOfSet - возвращает true, если множество содержит все заданные элементы, в противном случае - false.
HasEach(<пустой набор/множесто>) возвращает true
*/
func (v runeSet) HasEachOfSet(s runeSet) bool {
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

// Add - добавляет элементы в множество v
func (v runeSet) Add(kk ...rune) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

// AddSlice - добавляет элементы в множество v
func (v runeSet) AddSlice(kk []rune) {
	for _, k := range kk {
		v[k] = struct{}{}
	}
}

// AddSet - добавляет элементы в множество v
func (v runeSet) AddSet(s runeSet) {
	for k, _ := range s {
		v[k] = struct{}{}
	}
}

// Del - удаляет элементы из множествa v
func (v runeSet) Del(kk ...rune) {
	for _, k := range kk {
		delete(v, k)
	}
}

// DelSlice - удаляет элементы из множествa v
func (v runeSet) DelSlice(kk []rune) {
	for _, k := range kk {
		delete(v, k)
	}
}

// DelSet - удаляет элементы из множествa v
func (v runeSet) DelSet(s runeSet) {
	for k, _ := range s {
		delete(v, k)
	}
}

// Union - возвращает результат объединения двух множеств. Исходные множества остаются без изменений
func (v runeSet) Union(s runeSet) runeSet {
	result := v.Copy()
	result.AddSet(s)
	return result
}

// Intersect - возвращает результат пересечения двух множеств. Исходные множества остаются без изменений
func (v runeSet) Intersect(s runeSet) runeSet {
	result := runeSet{}
	for k, _ := range v {
		if _, ok := s[k]; ok {
			result[k] = struct{}{}
		}
	}
	return result
}

// Subtract - возвращает результат вычитания двух множеств. Исходные множества остаются без изменений
func (v runeSet) Subtract(s runeSet) runeSet {
	result := runeSet{}
	for k, _ := range v {
		if _, ok := s[k]; !ok {
			result[k] = struct{}{}
		}
	}
	return result
}

type _runeSlice []rune

func (v _runeSlice) Len() int {
	return len(v)
}

func (v _runeSlice) Swap(i int, j int) {
	v[i], v[j] = v[j], v[i]
}

func (v _runeSlice) Less(i int, j int) bool {
	return v[i] < v[j]
}
