// Code generated by "setter -type=unicodeCategory"; DO NOT EDIT github.com/baza-winner/bwcore/setter

package defparse

import (
	bwjson "github.com/baza-winner/bwcore/bwjson"
	"sort"
)

type unicodeCategorySet map[unicodeCategory]struct{}

func unicodeCategorySetFromArgs(kk ...unicodeCategory) unicodeCategorySet {
	return unicodeCategorySetFromSlice(kk)
}

func unicodeCategorySetFromSlice(kk []unicodeCategory) unicodeCategorySet {
	result := unicodeCategorySet{}
	for _, k := range kk {
		result[k] = struct{}{}
	}
	return result
}

func (v unicodeCategorySet) Copy() unicodeCategorySet {
	return unicodeCategorySetFromSlice(v.ToSlice())
}

func (v unicodeCategorySet) ToSlice() []unicodeCategory {
	result := _unicodeCategorySlice{}
	for k, _ := range v {
		result = append(result, k)
	}
	sort.Sort(result)
	return result
}

func (v unicodeCategorySet) String() string {
	return bwjson.PrettyJsonOf(v)
}

func (v unicodeCategorySet) GetDataForJson() interface{} {
	result := []interface{}{}
	for _, k := range v.ToSlice() {
		result = append(result, k.String())
	}
	return result
}

func (v unicodeCategorySet) ToSliceOfStrings() (result []string) {
	result = []string{}
	for k, _ := range v {
		result = append(result, k.String())
	}
	sort.Strings(result)
	return result
}

func (v unicodeCategorySet) ContainesEach(s unicodeCategorySet) bool {
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			return false
		}
	}
	return true
}

func (v unicodeCategorySet) ContainsAny(s unicodeCategorySet) bool {
	for k, _ := range s {
		if _, ok := v[k]; ok {
			return true
		}
	}
	return false
}

func (v unicodeCategorySet) Union(s unicodeCategorySet) {
	for k, _ := range s {
		v[k] = struct{}{}
	}
}

func (v unicodeCategorySet) Intersect(s unicodeCategorySet) {
	for k, _ := range v {
		if _, ok := s[k]; !ok {
			delete(v, k)
		}
	}
	for k, _ := range s {
		if _, ok := v[k]; !ok {
			delete(v, k)
		}
	}
}

func (v unicodeCategorySet) Subtract(s unicodeCategorySet) {
	for k, _ := range v {
		if _, ok := s[k]; ok {
			delete(v, k)
		}
	}
}

func _unicodeCategorySetUnion(s1 unicodeCategorySet, s2 unicodeCategorySet) unicodeCategorySet {
	s1.Union(s2)
	return s1
}

func _unicodeCategorySetIntersect(s1 unicodeCategorySet, s2 unicodeCategorySet) unicodeCategorySet {
	s1.Intersect(s2)
	return s1
}

func _unicodeCategorySetSubtract(s1 unicodeCategorySet, s2 unicodeCategorySet) unicodeCategorySet {
	s1.Subtract(s2)
	return s1
}

type _unicodeCategorySlice []unicodeCategory

func (v _unicodeCategorySlice) Len() int {
	return len(v)
}

func (v _unicodeCategorySlice) Swap(i int, j int) {
	v[i], v[j] = v[j], v[i]
}

func (v _unicodeCategorySlice) Less(i int, j int) bool {
	return v[i] < v[j]
}
