// Code generated by "stringer -type=unicodeCategory"; DO NOT EDIT.

package defparse

import "strconv"

const _unicodeCategory_name = "unicodeSpace"

var _unicodeCategory_index = [...]uint8{0, 12}

func (i unicodeCategory) String() string {
	if i >= unicodeCategory(len(_unicodeCategory_index)-1) {
		return "unicodeCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _unicodeCategory_name[_unicodeCategory_index[i]:_unicodeCategory_index[i+1]]
}
