// Code generated by "stringer -type=unicodeCategory,parseStackItemType,parsePrimaryState,parseSecondaryState,pfaErrorType,ruleKind"; DO NOT EDIT.

package defparse

import "strconv"

const _unicodeCategory_name = "unicodeSpaceunicodeLetterunicodeDigitunicodeOpenBracesunicodePunctunicodeSymbol"

var _unicodeCategory_index = [...]uint8{0, 12, 25, 37, 54, 66, 79}

func (i unicodeCategory) String() string {
	if i >= unicodeCategory(len(_unicodeCategory_index)-1) {
		return "unicodeCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _unicodeCategory_name[_unicodeCategory_index[i]:_unicodeCategory_index[i+1]]
}

const _parseStackItemType_name = "parseStackItem_below_parseStackItemKeyparseStackItemStringparseStackItemMapparseStackItemArrayparseStackItemQwparseStackItemQwItemparseStackItemNumberparseStackItemWordparseStackItem_above_"

var _parseStackItemType_index = [...]uint8{0, 21, 38, 58, 75, 94, 110, 130, 150, 168, 189}

func (i parseStackItemType) String() string {
	if i >= parseStackItemType(len(_parseStackItemType_index)-1) {
		return "parseStackItemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _parseStackItemType_name[_parseStackItemType_index[i]:_parseStackItemType_index[i+1]]
}

const _parsePrimaryState_name = "parsePrimaryState_below_expectEOFexpectValueOrSpaceexpectRocketexpectWordexpectDigitexpectContentOfexpectEscapedContentOfexpectSpaceOrMapKeyexpectSpaceOrQwItemOrDelimiterexpectEndOfQwItemparsePrimaryState_above_"

var _parsePrimaryState_index = [...]uint8{0, 24, 33, 51, 63, 73, 84, 99, 121, 140, 170, 187, 211}

func (i parsePrimaryState) String() string {
	if i >= parsePrimaryState(len(_parsePrimaryState_index)-1) {
		return "parsePrimaryState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _parsePrimaryState_name[_parsePrimaryState_index[i]:_parsePrimaryState_index[i+1]]
}

const _parseSecondaryState_name = "anySecondaryStatenoSecondaryStateorSpaceorMapKeySeparatororArrayItemSeparatororUnderscoreOrDotorUnderscorestringTokenkeyTokenorMapValueSeparator"

var _parseSecondaryState_index = [...]uint8{0, 17, 33, 40, 57, 77, 94, 106, 117, 125, 144}

func (i parseSecondaryState) String() string {
	if i >= parseSecondaryState(len(_parseSecondaryState_index)-1) {
		return "parseSecondaryState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _parseSecondaryState_name[_parseSecondaryState_index[i]:_parseSecondaryState_index[i+1]]
}

const _pfaErrorType_name = "pfaError_below_unexpectedRuneErrorfailedToGetNumberErrorunknownWordErrorpfaError_above_"

var _pfaErrorType_index = [...]uint8{0, 15, 34, 56, 72, 87}

func (i pfaErrorType) String() string {
	if i >= pfaErrorType(len(_pfaErrorType_index)-1) {
		return "pfaErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _pfaErrorType_name[_pfaErrorType_index[i]:_pfaErrorType_index[i+1]]
}

const _ruleKind_name = "ruleNormalruleDefaultruleEof"

var _ruleKind_index = [...]uint8{0, 10, 21, 28}

func (i ruleKind) String() string {
	if i >= ruleKind(len(_ruleKind_index)-1) {
		return "ruleKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ruleKind_name[_ruleKind_index[i]:_ruleKind_index[i+1]]
}
