// Code generated by "stringer -type=ParamType"; DO NOT EDIT.

package helper

import "strconv"

const _ParamType_name = "ParamBelowParamNoneParamArgParamArgsParamSliceParamSetParamIJParamAbove"

var _ParamType_index = [...]uint8{0, 10, 19, 27, 36, 46, 54, 61, 71}

func (i ParamType) String() string {
	if i >= ParamType(len(_ParamType_index)-1) {
		return "ParamType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParamType_name[_ParamType_index[i]:_ParamType_index[i+1]]
}
