// Code generated by "stringer -type=ParamsType"; DO NOT EDIT.

package helper

import "strconv"

const _ParamsType_name = "ptBelowptNoneptArgptArgsptSliceptSetptIJptAbove"

var _ParamsType_index = [...]uint8{0, 9, 15, 20, 26, 33, 38, 42, 51}

func (i ParamType) String() string {
	if i >= ParamType(len(_ParamsType_index)-1) {
		return "ParamsType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParamsType_name[_ParamsType_index[i]:_ParamsType_index[i+1]]
}
