// Code generated by "stringer -type=ReturnType"; DO NOT EDIT.

package helper

import "strconv"

const _ReturnType_name = "ReturnBelowReturnNoneReturnBoolReturnIntReturnInterfaceReturnJSONReturnStringReturnSetReturnSliceReturnSliceOfStringsReturnAbove"

var _ReturnType_index = [...]uint8{0, 11, 21, 31, 40, 55, 65, 77, 86, 97, 117, 128}

func (i ReturnType) String() string {
	if i >= ReturnType(len(_ReturnType_index)-1) {
		return "ReturnType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReturnType_name[_ReturnType_index[i]:_ReturnType_index[i+1]]
}
