// Code generated by "stringer -type=TestDataKind"; DO NOT EDIT.

package helper

import "strconv"

const _TestDataKind_name = "InOut"

var _TestDataKind_index = [...]uint8{0, 2, 5}

func (i TestDataKind) String() string {
	if i >= TestDataKind(len(_TestDataKind_index)-1) {
		return "TestDataKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestDataKind_name[_TestDataKind_index[i]:_TestDataKind_index[i+1]]
}
