// Code generated by "stringer -type=TestItem"; DO NOT EDIT.

package helper

import "strconv"

const _TestItem_name = "ab"

var _TestItem_index = [...]uint8{0, 1, 2}

func (i TestItem) String() string {
	if i >= TestItem(len(_TestItem_index)-1) {
		return "TestItem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestItem_name[_TestItem_index[i]:_TestItem_index[i+1]]
}
