// Code generated by "stringer -type=Item"; DO NOT EDIT.

package deftype

import "strconv"

const _Item_name = "Item_below_BoolStringIntNumberMapArrayArrayOfItem_above_"

var _Item_index = [...]uint8{0, 11, 15, 21, 24, 30, 33, 38, 45, 56}

func (i Item) String() string {
	if i >= Item(len(_Item_index)-1) {
		return "Item(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Item_name[_Item_index[i]:_Item_index[i+1]]
}
