// Code generated by "stringer -type=Item"; DO NOT EDIT.

package deftype

import "strconv"

const _Item_name = "ItemBelowBoolStringIntNumberMapArrayArrayOfItemAbove"

var _Item_index = [...]uint8{0, 9, 13, 19, 22, 28, 31, 36, 43, 52}

func (i Item) String() string {
	if i >= Item(len(_Item_index)-1) {
		return "Item(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Item_name[_Item_index[i]:_Item_index[i+1]]
}
