// Code generated by "stringer -type ValKind -trimprefix Val"; DO NOT EDIT.

package bwtype

import "strconv"

const _ValKind_name = "UnknownNilStringBoolIntUintFloat64NumberPathRangeMapArrayArrayOfStringArrayOf"

var _ValKind_index = [...]uint8{0, 7, 10, 16, 20, 23, 27, 34, 40, 44, 49, 52, 57, 70, 77}

func (i ValKind) String() string {
	if i >= ValKind(len(_ValKind_index)-1) {
		return "ValKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValKind_name[_ValKind_index[i]:_ValKind_index[i+1]]
}
