// Code generated by "stringer -type ValKind -trimprefix Val"; DO NOT EDIT.

package bwtype

import "strconv"

const _ValKind_name = "UnknownNilBoolIntFloat64NumberStringArrayArrayOfStringArrayOfMapKindAbove"

var _ValKind_index = [...]uint8{0, 7, 10, 14, 17, 24, 30, 36, 41, 54, 61, 64, 73}

func (i ValKind) String() string {
	if i >= ValKind(len(_ValKind_index)-1) {
		return "ValKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValKind_name[_ValKind_index[i]:_ValKind_index[i+1]]
}
